const gate=document.getElementById('gate'),begin=document.getElementById('begin'),music=document.getElementById('music'),video=document.getElementById('memoryVideo'),videoPlay=document.getElementById('videoPlay'),confess=document.getElementById('confess'),secret=document.getElementById('secret');
const scenes=[...document.querySelectorAll('.scene')],frames=[...document.querySelectorAll('.frame')];
let player,wantsMusic=false,musicPlaying=false,current=0,frameIndex=0,changing=false,songStarted=false;
const labels=['Başlangıç','Seni gördüğüm yer','Anılarımız','Sana söylemek istediğim','Gülüşün','Videomuz','Ufak bir isyan','Bizden kareler','Sözlerim','Ezgi kılavuzu','Gelecekten kartpostal','Acil durum paketi','Kalbim','Daima'];
const dots=document.createElement('div'),chapterLabel=document.createElement('div');
dots.className='chapter-dots';chapterLabel.className='chapter-label';document.body.append(dots,chapterLabel);
scenes.forEach(()=>dots.appendChild(document.createElement('i')));
function paint(){[...dots.children].forEach((d,i)=>d.className=i<current?'done':i===current?'current':'');chapterLabel.textContent=labels[current]||'Biz'}
function showScene(next){if(changing||next<0||next>=scenes.length)return;changing=true;scenes[current].classList.remove('story-active');scenes[current].classList.add('story-past');current=next;scenes[current].classList.remove('story-past');scenes[current].classList.add('story-active');scenes[current].scrollTop=0;paint();setTimeout(()=>changing=false,700)}
scenes.forEach((scene,i)=>{if(i===scenes.length-1)return;const btn=document.createElement('button');btn.className='story-next'+(['02','05','08','09','∞'].includes(scene.dataset.chapter)?' paper-next':'');btn.innerHTML='<span>Devam et</span><b>→</b>';scene.appendChild(btn);if(scene.classList.contains('film')){btn.querySelector('span').textContent='Sonraki fotoğraf';btn.addEventListener('click',()=>{if(frameIndex<frames.length-1){frames[frameIndex].classList.remove('memory-active');frameIndex++;frames[frameIndex].classList.add('memory-active');btn.querySelector('span').textContent=frameIndex===frames.length-1?'Üçünü de gördüm':'Sonraki fotoğraf'}else showScene(i+1)})}else btn.addEventListener('click',()=>showScene(i+1));if(scene.classList.contains('video-scene')){btn.disabled=true;btn.querySelector('span').textContent='Önce videomuzu izle'}});
scenes[0].classList.add('story-active');frames[0]?.classList.add('memory-active');paint();
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player('yt',{height:'1',width:'1',videoId:'wB8x81sXd48',playerVars:{playsinline:1,controls:0,loop:1,playlist:'wB8x81sXd48'},events:{onReady:()=>wantsMusic&&playMusic(),onStateChange:e=>{musicPlaying=e.data===YT.PlayerState.PLAYING;music.classList.toggle('paused',!musicPlaying)}}})};
function playMusic(){if(player?.playVideo){if(!songStarted){player.seekTo(32,true);songStarted=true}player.playVideo();musicPlaying=true;music.classList.remove('paused')}}
function pauseMusic(){if(player?.pauseVideo){player.pauseVideo();musicPlaying=false;music.classList.add('paused')}}
begin.addEventListener('click',()=>{wantsMusic=true;gate.classList.add('leave');playMusic();burst(22);setTimeout(()=>gate.remove(),1100)});
music.addEventListener('click',()=>musicPlaying?pauseMusic():playMusic());
videoPlay.addEventListener('click',()=>{pauseMusic();video.controls=true;video.play();videoPlay.classList.add('hide')});
video.addEventListener('pause',()=>{if(!video.ended)videoPlay.classList.remove('hide')});
video.addEventListener('ended',()=>{video.controls=false;videoPlay.classList.remove('hide');playMusic();const btn=document.querySelector('.video-scene .story-next');btn.disabled=false;btn.querySelector('span').textContent='Anımızla devam et'});
confess.addEventListener('click',()=>{secret.classList.add('open');confess.closest('.confession').classList.add('letter-open');confess.textContent='İyi ki sen ♡';confess.disabled=true;for(let i=0;i<38;i++)setTimeout(dropTear,i*75)});
function dropTear(){const t=document.createElement('i');t.className='tear';t.style.left=(4+Math.random()*92)+'vw';t.style.setProperty('--speed',(2.2+Math.random()*2.7)+'s');t.style.opacity=.3+Math.random()*.65;document.body.appendChild(t);setTimeout(()=>t.remove(),5200)}
function burst(n){for(let i=0;i<n;i++)setTimeout(()=>{const h=document.createElement('i');h.className='heart';h.textContent=Math.random()>.5?'♥':'♡';h.style.left=(42+Math.random()*16)+'vw';h.style.top='78vh';h.style.fontSize=(12+Math.random()*20)+'px';h.style.setProperty('--x',(-160+Math.random()*320)+'px');document.body.appendChild(h);setTimeout(()=>h.remove(),1900)},i*45)}
document.querySelectorAll('.reveal').forEach(el=>el.classList.add('on'));
document.querySelector('.light-copy')?.insertAdjacentHTML('beforeend','<div class="fun-note">Görev dağılımı: Sen gülümse, ben sebep bulurum. Kötü şaka departmanı da şimdilik bende.</div>');
document.querySelector('.rebellion-copy')?.insertAdjacentHTML('beforeend','<div class="fun-note">Özlemek edebiyatta güzel. Gerçek hayatta gereksiz masraf.</div>');

// Her bölümün sonunda açılan kısa, farklı mini oyunlar
const games=[
 {type:'tap',q:'Kaçak kalp alarmı',hint:'Kalbi 6 kez yakala. Seni görünce yerinde duramıyor.',win:'Yakaladın. Zaten kaçtığı yer hep sendin.',tease:'Sıradaki sayfada seni nasıl gördüğümü anlatacağım.'},
 {type:'choice',q:'Mini Ezgi testi',hint:'“İyiyim” diyen Ezgi’ye en doğru yaklaşım?',choices:['Tamam deyip gitmek','Yanında kalıp gerçekten sormak','Telefonu uçak moduna almak'],ok:1,win:'Doğru cevap: yanında kalmak.',tease:'Bir sonraki sayfada yakından bir anımız var.'},
 {type:'hold',q:'Anıyı mühürle',hint:'Kalbe 2 saniye basılı tut. Güzel anılar aceleye gelmez.',win:'Bu anı kalbimize kaydedildi.',tease:'Sırada yüklerinden bir ucunu tutmak var.'},
 {type:'release',q:'Yükleri bırak',hint:'Üzerlerine dokun; bugün hiçbirini tek başına taşımıyorsun.',items:['Kaygı','Yorgunluk','Kırgınlık','Güçlü görünme çabası'],win:'Birazı bende. Şimdi daha hafifiz.',tease:'Sonra seni izlerken yakalandığım kare geliyor.'},
 {type:'memory',q:'Kalp hafızası',hint:'Aynı iki sembolü eşleştir. Hafızamda en net olan sensin.',cards:['♡','☕','♡','☕'],win:'Eşleşme başarılı: Ali + Ezgi.',tease:'Sırada hareketli bir anımız var.'},
 {type:'sequence',q:'Bizim formülümüz',hint:'Doğru sırayla dokun: önce bakış, sonra gülüş, sonra kalp.',sequence:['👀','😊','❤️'],win:'Formül çalıştı. Yan etkisi: daha çok özlemek.',tease:'Bir sonraki bölümde ufak bir isyanım var.'},
 {type:'slider',q:'Mesafeyi kapat',hint:'Kalbi Ezgi’ye kadar kaydır.',win:'Mesafe kapandı. Olması gereken de buydu.',tease:'Az sonra anılarımızdan küçük bir duvar açılacak.'},
 {type:'stars',q:'Bu hikâyeye puan ver',hint:'Devam etmek için yıldızları tek tek yak. Beşincisi biraz şımarık.',win:'Beş yıldız mı? Ben Ezgi’ye altı verirdim.',tease:'Sonraki sayfada büyük değil, gerçek sözler var.'},
 {type:'choice',q:'Zor gün testi',hint:'Zor bir günde en güzel iki kelime hangisi?',choices:['Geçer ya','Abartıyorsun','Ben buradayım'],ok:2,win:'Bazen en güzel yardım gerçekten iki kelime.',tease:'Bir sonraki sayfada kalbimin kapısı var.'},
 {type:'sequence',q:'Ezgi protokolü',hint:'Doğru sırayı kur: kahve, gülüş, sarılma.',sequence:['☕','😊','🤗'],win:'Protokol başarıyla çalıştı.',tease:'Şimdi gelecekten gelen bir mesaj var.'},
 {type:'mystery',q:'Gelecekten gelen zarf',hint:'Kartpostalın devamını taşıyan zarfı seç.',win:'Gelecekteki biz bu seçimi onayladı.',tease:'Sırada kötü günler için gizli bir paket var.'},
 {type:'release',q:'Acil durum çantasını hazırla',hint:'Dört malzemeye de dokunup çantaya ekle.',items:['Sarılma +','Kahve +','Sabır +','Kötü şaka +'],win:'Paket hazır. Teslimat adresi: Ezgi’nin yanı.',tease:'Şimdi kalbimin son kapısına geldik.'},
 {type:'hold',q:'Son kalp mührü',hint:'Kalbe basılı tut ve son mektubun kilidini aç.',win:'Kalp doğrulandı: sahibi Ezgi.',tease:'Hazırsan hikâyenin son cümlesine gidiyoruz.'}
];
const cleared=new WeakSet();let gameOpen=false;
document.addEventListener('click',e=>{const btn=e.target.closest('.story-next');if(!btn||btn.disabled)return;const scene=btn.closest('.scene');if(!scene||cleared.has(scene)||gameOpen)return;e.preventDefault();e.stopImmediatePropagation();openGame(scene,btn)},true);
function openGame(scene,trigger){
 gameOpen=true;const data=games[Math.min(current,games.length-1)],overlay=document.createElement('div');overlay.className='game-overlay';overlay.innerHTML='<div class="game-sheet" role="dialog" aria-modal="true"><span class="game-kicker">SÜRPRİZ GÖREV · '+String(current+1).padStart(2,'0')+'</span><h3>'+data.q+'</h3><p>'+data.hint+'</p><div class="game-play"></div><small>Görevi tamamla, sıradaki sürprizin kilidi açılsın.</small></div>';document.body.appendChild(overlay);const play=overlay.querySelector('.game-play'),note=overlay.querySelector('small');requestAnimationFrame(()=>overlay.classList.add('show'));
 const finish=()=>{play.classList.add('completed');note.innerHTML='<b>'+data.win+'</b><br>'+data.tease;burst(14);setTimeout(()=>{cleared.add(scene);overlay.classList.remove('show');setTimeout(()=>{overlay.remove();gameOpen=false;trigger.click()},280)},1550)};
 if(data.type==='choice'){play.className='game-play game-choices';play.innerHTML=data.choices.map((x,i)=>'<button data-choice="'+i+'">'+x+'</button>').join('');play.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(Number(x.dataset.choice)===data.ok){x.classList.add('right');finish()}else{x.classList.remove('wrong');void x.offsetWidth;x.classList.add('wrong');note.textContent='Kalbim “bir daha düşün” diyor 😄'}})}
 if(data.type==='tap'){let n=0;play.className='game-play tap-zone';play.innerHTML='<button class="run-heart">♥</button><b>0 / 6</b>';const h=play.querySelector('button'),count=play.querySelector('b'),move=()=>{h.style.left=(5+Math.random()*72)+'%';h.style.top=(8+Math.random()*48)+'%'};move();h.onclick=()=>{n++;count.textContent=n+' / 6';burst(2);n===6?finish():move()}}
 if(data.type==='hold'){play.className='game-play hold-zone';play.innerHTML='<button class="hold-heart"><i></i><span>♡</span></button><b>Basılı tut</b>';const h=play.querySelector('button');let timer;const start=()=>{h.classList.add('holding');timer=setTimeout(finish,1800)},stop=()=>{clearTimeout(timer);h.classList.remove('holding')};h.onpointerdown=start;h.onpointerup=stop;h.onpointerleave=stop;h.oncontextmenu=e=>e.preventDefault()}
 if(data.type==='release'){play.className='game-play release-zone';play.innerHTML=data.items.map(x=>'<button>'+x+' ×</button>').join('');let left=data.items.length;play.querySelectorAll('button').forEach(x=>x.onclick=()=>{x.classList.add('released');if(--left===0)setTimeout(finish,350)})}
 if(data.type==='memory'){play.className='game-play memory-zone';play.innerHTML=data.cards.map((x,i)=>'<button data-value="'+x+'" data-card="'+i+'"><span>?</span></button>').join('');let open=[],pairs=0;play.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(x.classList.contains('open')||open.length===2)return;x.classList.add('open');x.querySelector('span').textContent=x.dataset.value;open.push(x);if(open.length===2)setTimeout(()=>{if(open[0].dataset.value===open[1].dataset.value){open.forEach(c=>c.classList.add('matched'));pairs++;if(pairs===2)finish()}else open.forEach(c=>{c.classList.remove('open');c.querySelector('span').textContent='?'});open=[]},500)})}
 if(data.type==='sequence'){play.className='game-play sequence-zone';play.innerHTML=[...data.sequence].reverse().map(x=>'<button>'+x+'</button>').join('')+'<div></div>';let pos=0;const line=play.querySelector('div');play.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(x.textContent===data.sequence[pos]){x.disabled=true;x.classList.add('right');line.textContent+=x.textContent+' ';if(++pos===data.sequence.length)finish()}else{line.textContent='Sıra karıştı 😄 ';x.classList.add('wrong');setTimeout(()=>x.classList.remove('wrong'),400)}})}
 if(data.type==='slider'){play.className='game-play slider-zone';play.innerHTML='<span>Ali</span><input type="range" min="0" max="100" value="0" aria-label="Kalbi Ezgi’ye taşı"><span>Ezgi ♡</span>';play.querySelector('input').oninput=e=>{if(e.target.value>94){e.target.disabled=true;finish()}}}
 if(data.type==='stars'){play.className='game-play stars-zone';play.innerHTML='★★★★★'.split('').map((x,i)=>'<button data-star="'+i+'">☆</button>').join('');let star=0;play.querySelectorAll('button').forEach(x=>x.onclick=()=>{if(Number(x.dataset.star)!==star)return;x.textContent='★';x.classList.add('lit');if(++star===5)finish()})}
 if(data.type==='mystery'){play.className='game-play mystery-zone';play.innerHTML='<button>💌<span>1</span></button><button>💌<span>2</span></button><button>💌<span>3</span></button>';play.querySelectorAll('button').forEach((x,i)=>x.onclick=()=>{play.querySelectorAll('button').forEach(b=>b.disabled=true);x.innerHTML='❤️<span>Buldun!</span>';x.classList.add('found');setTimeout(finish,450)})}
}
